pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS = credentials('DOCKER_CREDENTIALS')
    }

    tools {
        git 'Default'  // Utilisez le nom de l'installation que vous avez configuré pour Git
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/malekkammoun/Segmentation.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    // Spécifiez le contexte de build explicitement
                    docker.build('my-flask-app:latest', '.')
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    docker.image('my-flask-app:latest').inside {
                        sh 'pip install -r requirements.txt'
                        sh 'pytest'
                    }
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    sh "echo ${DOCKER_CREDENTIALS_PSW} | docker login -u ${DOCKER_CREDENTIALS_USR} --password-stdin"
                    docker.image('my-flask-app:latest').push('latest')
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
